<html><head>


<!-- Load require.js. Delete this if your page already loads require.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js" integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>
<script type="application/vnd.jupyter.widget-state+json">
{
    "version_major": 2,
    "version_minor": 0,
    "state": {}
}
</script>
</head>
<body>
    <h1>All-Pairs Shortest Paths - Floyd–Warshall Algorithm</h1>    
    <h2>Dynamic Programming Approach</h2>
    <img src="Floyd-Warshall-Graph.PNG"/>
    <h2 align="center">Graph</h2>
</body>
</html>

In [1]:
import numpy as np
import math as mt

In [2]:
a = np.array([[0, 3, mt.inf, 7], [8, 0, 2, mt.inf], [5, mt.inf, 0, 1], [2, mt.inf, mt.inf, 0]])
n = a.shape[0]
print("Initial Matrix")
print(a)

Initial Matrix
[[ 0.  3. inf  7.]
 [ 8.  0.  2. inf]
 [ 5. inf  0.  1.]
 [ 2. inf inf  0.]]


In [3]:
for k in range(n):
    print("Through Vertex: "+str(k+1))
    for i in range(n):
        for j in range(n):
            a[i,j] = min(a[i,j],a[i,k]+a[k,j])
    print(a)
    if k != n-1:
        print("\n")

Through Vertex: 1
[[ 0.  3. inf  7.]
 [ 8.  0.  2. 15.]
 [ 5.  8.  0.  1.]
 [ 2.  5. inf  0.]]


Through Vertex: 2
[[ 0.  3.  5.  7.]
 [ 8.  0.  2. 15.]
 [ 5.  8.  0.  1.]
 [ 2.  5.  7.  0.]]


Through Vertex: 3
[[0. 3. 5. 6.]
 [7. 0. 2. 3.]
 [5. 8. 0. 1.]
 [2. 5. 7. 0.]]


Through Vertex: 4
[[0. 3. 5. 6.]
 [5. 0. 2. 3.]
 [3. 6. 0. 1.]
 [2. 5. 7. 0.]]
